version: "3.7"
services:
  backend:
    build: ./backend
    restart: always
    networks:
      - overlay
    volumes:
      - ./data/logs/backend:/usr/backend/logs
      # - ~/.aws/:/root/.aws:ro #aws credetials
  
  frontend:
    build: ./frontend
    restart: always
    networks:
      - overlay
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - ./data/logs/frontend:/usr/frontend/logs
      # - ~/.aws/:/root/.aws:ro #aws credetials

  dashboard:
    build: ./dashboard
    restart: always
    networks:
      - overlay
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - ./data/logs/dashboard:/usr/dashboard/logs
      # - ~/.aws/:/root/.aws:ro #aws credetials

  nginx:
    restart: always
    build:
      context: ./nginx
      #args:
        #- BUILD_TYPE=${BUILD}
    ports:
      - "80:8080"
      - "443:8080"
    networks:
      - overlay
    volumes:
      - ./data/logs/nginx:/var/log/nginx
      - ~/etc/nginx/passwd:/etc/nginx/passwd
    links:
      - backend
      - dashboard
      - frontend
    depends_on:
      - backend
      - dashboard
      - frontend

networks:
  overlay:
